### ISSUE TITLE
Expose client socket information to Agent upon initiating Session

### ISSUE THREAD

**Issue by jcspencer** [wiktor-k/ssh-agent-lib#55]
Upon diving in to writing an agent, I've noticed there's one thing I'd love to get access to: information about the socket a client connected over.

This differs slightly by the platform / protocol:
- Unix sockets: `accept(self).await` returns a tuple which includes a `tokio::net::unix::SocketAddr`
- TCP sockets: `accept(self).await` returns a tuple which includes a `std::net::SocketAddr`
- Named Pipes (Windows): the server itself implements [`AsHandle`](https://docs.rs/tokio/latest/tokio/doc/os/windows/io/trait.AsHandle.html)
  - Note: On a named pipe, you can get information about a client from the pipe's handle, see [Win32-OpenSSH](https://github.com/PowerShell/openssh-portable/blob/607df771b2085f793e1dc393ec445eac2d66da5e/contrib/win32/win32compat/ssh-agent/agent.c#L290) for how this works.
  - As a client you'd have to call something like [`GetNamedPipeClientProcessId`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getnamedpipeclientprocessid) on the handle, but that'd require delving into unsafe code, and is probably outside the scope of this crate.
  - Essentially you'd be doing something like:
     - ```rust
        let mut pid: ULONG = 0;
        unsafe {
            GetNamedPipeClientProcessId(pipe.as_raw_handle() as HANDLE, &mut pid);
        }
        ```

This would allow an agent to ensure the client is coming from a trusted location. In my use-case (Named Pipes on Windows, sadly...), I'd want to make sure the client user's token matches the user that started up the agent. 

Happy to tackle this one if there's appetite! Let me know if this would be useful to add.

---

I imagine the change would be something like:

```rust
/// Enum containing socket information from
/// SSH agent clients
#[derive(Debug)]
pub enum ClientSocket<'a> {
    /// Unix pipe socket address
    #[cfg(unix)]
    Unix(tokio::net::unix::SocketAddr),

    /// TCP socket address
    Tcp(std::net::SocketAddr),

    /// Windows named pipe handle
    #[cfg(windows)]
    NamedPipe(std::os::windows::io::BorrowedHandle<'a>),
}

/// Type representing a socket that asynchronously returns a list of streams.
#[async_trait]
pub trait ListeningSocket {
    /// Stream type that represents an accepted socket.
    type Stream: fmt::Debug + AsyncRead + AsyncWrite + Send + Unpin + 'static;

    /// Waits until a client connects and returns connected stream.
    async fn accept(&mut self) -> io::Result<(Self::Stream, ClientSocket)>;
}
```

And then passing the resulting `ClientSocket` over to the session? Perhaps like:

```rust
pub trait Agent: 'static + Sync + Send + Sized {
    /// Create new session object when a new socket is accepted.
    fn new_session(&mut self, client: ClientSocket) -> impl Session;
}
```

---

I will note Windows named pipe handles are a bit more tricky than TCP/Unix socket information 😬

**Comment by wiktor-k** [comment]
Okay, this definitely is "in scope". Actually I've been thinking about something similar already:

```diff
diff --git a/src/agent.rs b/src/agent.rs
index 537e4c6..15f36d7 100644
--- a/src/agent.rs
+++ b/src/agent.rs
@@ -253,7 +253,9 @@ where
 #[async_trait]
 pub trait Agent: 'static + Sync + Send + Sized {
     /// Create new session object when a new socket is accepted.
-    fn new_session(&mut self) -> impl Session;
+    fn new_session<S>(&mut self, socket: &S::Stream) -> impl Session
+    where
+        S: ListeningSocket + fmt::Debug + Send;
 
     /// Listen on a socket waiting for client connections.
     async fn listen<S>(mut self, mut socket: S) -> Result<(), AgentError>
@@ -264,7 +266,7 @@ pub trait Agent: 'static + Sync + Send + Sized {
         loop {
             match socket.accept().await {
                 Ok(socket) => {
-                    let session = self.new_session();
+                    let session = self.new_session::<S>(&socket);
                     tokio::spawn(async move {
                         let adapter = Framed::new(socket, Codec::<Request, Response>::default());
                         if let Err(e) = handle_socket::<S>(session, adapter).await {
@@ -306,7 +308,10 @@ impl<T> Agent for T
 where
     T: Default + Session,
 {
-    fn new_session(&mut self) -> impl Session {
+    fn new_session<S>(&mut self, _socket: &S::Stream) -> impl Session
+    where
+        S: ListeningSocket + fmt::Debug + Send,
+    {
         Self::default()
     }
 }
```

But it seems you want to have access to the stuff that we discard in the `accept` call :thinking: 

If you don't mind I'd like to think about it a moment too. The small issues I see with your design is that even though we've got `ListeningSocket` type (that in theory could be implemented by outside crates) the `ClientSocket` constrains the result to only 3 types that we support here... I don't know if that's a problem but it's one minor thing that bothers me :sweat_smile:

**Comment by jcspencer** [comment]
Having a bit of a think about your design:

> ```diff
> diff --git a/src/agent.rs b/src/agent.rs
> index 537e4c6..15f36d7 100644
> --- a/src/agent.rs
> +++ b/src/agent.rs
> @@ -253,7 +253,9 @@ where
>  #[async_trait]
>  pub trait Agent: 'static + Sync + Send + Sized {
>      /// Create new session object when a new socket is accepted.
> -    fn new_session(&mut self) -> impl Session;
> +    fn new_session<S>(&mut self, socket: &S::Stream) -> impl Session
> +    where
> +        S: ListeningSocket + fmt::Debug + Send;
> ```

This actually be enough for a user implementation to get a reference to the NamedPipeServer, with would let them pull the information from it themselves. Also, it seems users can call [`peek_addr(&self)`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.peer_addr) on a socket to get information about the peer.

I think we can probably avoid implementing too much of this in the core library, and instead just provide some examples on how to pull that information from the reference to the `Stream` we provide?

--

Do you have a branch where you're working on something like what you showed in your diff above? It seems it'd solve the problem I'm facing without adding more constraining types

**Comment by wiktor-k** [comment]
I've pushed the change to https://github.com/wiktor-k/ssh-agent-lib/pull/60 so if you'd like to see what's going on try it out.

I'm still not sure if one can inspect that socket stream since it's generic you can't use peek_addr and friends... maybe the `<S>` generic argument needs to be moved to Agent or to the associated type?

I'll leave that as an exercise for the reader :wink:

**Comment by jcspencer** [comment]
Closing in favor of #60
